# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "omegaUp blog Gohugo Theme"
license = "MIT"
licenselink = "https://github.com/omegaup/omegaup/blob/master/LICENSE.md"
description = "The omegaUp blog theme. Based on ananke by spf13."
homepage = "https://github.com/omegaup/omegaup"
tags = ["omegaup"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.64.0"

[author]
  name = "The omegaUp Authors"
  homepage = "https://omegaup.org"
